   # This is a basic workflow to help you get started with Actions
name: Reserving Diner For my Tommy
on:
   push:
      branches:
         - master
   schedule: 
    - cron: '0 0 * * 2'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.8.1
        with: 
          node-version: '10.x'
      - run : dir
      - run: npm install 
      - run: npm run start
