    # This is a basic workflow to help you get started with Actions
name: Reserving Diner For my Tommy
on:
   push:
      branches:
         - master
   schedule: 
    - cron: '0 0 * * 2'
jobs:

  deploy:
    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get current working directory
      run: |
       echo "Files in current directory:"
       ls
       echo "Files in parent directory:"
       ls ..
       echo "Files in parent directory:"
       ls ../..
      
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"

    - name: Install dependencies
      run: npm install

    - name: Install Chromium
      run: sudo apt-get install chromium-browser

    - name: Set environment variable
      run: echo "CHROME_PATH=$(which google-chrome)" >> $GITHUB_ENV

    - name: RunApp
      run: npm run start 
